const { TAGS } = require('./catalog');

/**
 * The document's frame: what wraps the generated paths and schemas.
 *
 * The long `info.description` is deliberate. Six things about this API are true
 * of every endpoint and impossible to infer from any single one — the envelope,
 * the two token audiences, the society pin, money as decimal strings, soft
 * deletes, and how a list is paginated. Repeating them per operation would be
 * noise; leaving them out would make the document unusable.
 */

const OVERVIEW = `
The society management API: **460 endpoints** across four audiences — a super
admin, a society's own committee, the resident app, and the gate device.

---

## 1. Everything answers in one envelope

Success and failure use the same two keys. There is no \`ok\` flag: the HTTP
status carries that.

\`\`\`json
{ "message": "List fetched successfully", "result": { "notices": [], "pagination": {} } }
\`\`\`

\`\`\`json
{ "message": "You are not authorized", "result": {} }
\`\`\`

An empty result is \`{}\`, not \`null\` and not \`[]\` — a quirk of the original
service that clients depend on, so it is preserved.

## 2. Two token audiences, on two secrets

| Audience | Sign in with | Header | Opens |
|---|---|---|---|
| **Society admin** | \`POST /api/v1/auth/verify-otp\` | \`Authorization: Bearer …\` **+** \`x-society-id\` | \`/super-admin/*\`, \`/society-admin/*\` |
| **Resident** | \`POST /api/v1/app/users/verify-otp\` | \`Authorization: Bearer …\` | \`/app/*\`, and \`/gatekeeper/*\` for a posted guard |

They are signed with **different secrets**, so a resident token presented to an
admin route fails signature verification — it is not merely a role check that
could be forgotten somewhere. Tokens are stateless; \`logout\` records the token
as revoked and it is refused from that moment.

### Signing in as a chairman

\`\`\`bash
curl -X POST http://localhost:3000/api/v1/auth/send-otp \\
  -H 'content-type: application/json' \\
  -d '{"societyCode":"SOC-2026-001","countryCode":"+91","phoneNumber":"9876543210"}'

curl -X POST http://localhost:3000/api/v1/auth/verify-otp \\
  -H 'content-type: application/json' \\
  -d '{"societyCode":"SOC-2026-001","countryCode":"+91","phoneNumber":"9876543210","otp":"123456"}'
\`\`\`

\`\`\`json
{
  "message": "OTP is verified successfully.",
  "result": {
    "_id": "6a9fa4f2deabbff67a50992f",
    "phoneNumber": "9876543210",
    "fullName": "Hemant Shah",
    "role": ["Chairman"],
    "societyId": "6a9fa4f2660a9babaf76744d",
    "societyCode": "SOC-2026-001",
    "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9…"
  }
}
\`\`\`

Then every admin call carries **both** headers:

\`\`\`bash
curl http://localhost:3000/api/v1/society-admin/notices \\
  -H "Authorization: Bearer $TOKEN" \\
  -H "x-society-id: 6a9fa4f2660a9babaf76744d"
\`\`\`

The society code is not decoration: an admin's phone number is unique only
*within* a society, so it is part of the identity being claimed — and it is
re-checked on verify, not only on send.

In development, set \`SOCIETY_OTP_DEV_CODE=123456\` and every OTP is that code.
It is ignored when \`NODE_ENV=production\`. OTPs are stored **hashed** and are
never returned in a response.

## 3. Which society a call is about

Two mechanisms, for two different reasons:

- **\`x-society-id\` header** on the admin and gate surfaces. Validated against
  the caller's own assignments on *every* request — a valid token for society A
  cannot read society B. A missing header is **400**; a society the caller does
  not administer is **401**.
- **\`?societyId=\` query parameter** on the resident surface, because one person
  may hold flats in several societies and their token says who they are, not
  which building they are looking at.

## 4. Money is a decimal string of rupees

Storage is integer **paise**, so a percentage late fee across four hundred units
cannot drift in floating point. The conversion happens once, at this boundary.

\`\`\`json
{ "amount": "2500", "gstAmount": "450.5", "outstanding": "0" }
\`\`\`

Send the same form on the way in. An amount that is not set stays \`null\` —
"not set" is not "free".

## 5. Nothing is really deleted

\`DELETE\` sets \`isDeleted: true\` and returns the row. Every list filters it
out. History, audit trails and references survive.

## 6. Lists

\`\`\`json
{
  "message": "List fetched successfully",
  "result": {
    "notices": [ { "…": "…" } ],
    "pagination": { "total": 42, "page": 1, "limit": 10, "totalPages": 5 }
  }
}
\`\`\`

The array sits under a key named for the resource, never \`data\`. The page-size
parameter is \`limit\` on some endpoints and \`perPage\` on others — the two
generations of the original service disagreed, and each endpoint keeps the
spelling its clients already send. Each operation below states which it takes.

---

*Generated by \`npm run society:openapi\` from the mounted routers, the Mongoose
schemas and the middleware actually guarding each route. Do not edit by hand —
edit the code, or the prose in \`scripts/society-openapi/catalog.js\`.*
`.trim();

module.exports = function document({ paths, schemas, usedTags, count }) {
  return {
    openapi: '3.1.0',
    info: {
      title: 'Society Management API',
      version: '1.0.0',
      summary: `${count} endpoints for society administration, the resident app and the gate.`,
      description: OVERVIEW,
      license: { name: 'Proprietary — Shivalik Group', identifier: 'LicenseRef-Proprietary' },
    },
    servers: [
      { url: 'http://localhost:3000', description: 'Local development' },
      { url: '{origin}', description: 'Any deployment', variables: { origin: { default: 'https://crm.example.com' } } },
    ],
    tags: TAGS.filter((t) => usedTags.has(t.name)),
    paths,
    components: {
      securitySchemes: {
        societyAdminToken: {
          type: 'http',
          scheme: 'bearer',
          bearerFormat: 'JWT',
          description: 'From `POST /api/v1/auth/verify-otp`. Signed with the **admin** '
            + 'secret and valid for 7 days. A bare token without the `Bearer ` prefix is '
            + 'also accepted, because the original clients send it that way.',
        },
        residentToken: {
          type: 'http',
          scheme: 'bearer',
          bearerFormat: 'JWT',
          description: 'From `POST /api/v1/app/users/verify-otp`. Signed with the **user** '
            + 'secret and valid for 30 days. The gate device uses one of these too — its '
            + 'authority is the holder\'s live posting to the society, not the token.',
        },
        societyId: {
          type: 'apiKey',
          in: 'header',
          name: 'x-society-id',
          description: 'The society this call is about. Re-checked against the caller\'s '
            + 'assignments on every request.',
        },
      },
      schemas: {
        ...schemas,
        Envelope: {
          type: 'object',
          description: 'The shape of every response from every endpoint.',
          required: ['message', 'result'],
          properties: {
            message: { type: 'string', example: 'List fetched successfully' },
            result: {
              description: 'The payload. `{}` when there is nothing to return — never `null`.',
              example: {},
            },
          },
        },
        Error: {
          type: 'object',
          description: 'A failure. Same two keys as a success; the status code carries the '
            + 'difference. `result` is `{}`, or an array of field errors on a validation failure.',
          required: ['message', 'result'],
          properties: {
            message: { type: 'string', example: 'You are not authorized' },
            result: {
              oneOf: [
                { type: 'object' },
                {
                  type: 'array',
                  items: {
                    type: 'object',
                    properties: { field: { type: 'string' }, message: { type: 'string' } },
                  },
                },
              ],
              example: {},
            },
          },
        },
        Pagination: {
          type: 'object',
          description: 'Accompanies every list. `limit` is named `perPage` on the endpoints '
            + 'that say so, and `hasNextPage`/`hasPrevPage` appear only where the original '
            + 'service emitted them.',
          properties: {
            total: { type: 'integer', example: 42 },
            page: { type: 'integer', example: 1 },
            limit: { type: 'integer', example: 10 },
            totalPages: { type: 'integer', example: 5 },
            hasNextPage: { type: 'boolean', example: true },
            hasPrevPage: { type: 'boolean', example: false },
          },
        },
      },
    },
  };
};
